name: prepare release

on:
  push:
    branches: [ 'release' ]

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    continue-on-error: false
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v4
        with:
          node-version: '24.14.0'
      - run: npm install
      - run: npm run test
      - run: npm run build
      - name: create new tag
        run: |
          # setup local git config user and e-mail
          git config --local user.email "action@github.com"
          git config --local user.name "release workflow action"
          # use npm version to update version in package.json
          npm version minor -m "create tagged release %s" --force
          # push created release version commit and tags
          git push --force && git push --tags --force
          # merge release back to main
          git checkout main
          git merge release
