name: release

on:
  workflow_dispatch:
  workflow_run:
    workflows: [ prepare release ]
    types:
      - completed

permissions:
  contents: write

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Retrieve version
        run: echo "TAG_NAME=$(git describe --tags --abbrev=0)')" >> $GITHUB_OUTPUT
        id: version
      - name: create release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.version.outputs.TAG_NAME }}
          files: 'dist/chuckNorrisJokeGenerator/browser/**/*'
